#!/usr/bin/env bun

import path from 'path';
import fs from 'fs/promises';
import { $ } from "bun";

const WIKI_URL = 'https://de.wikipedia.org/wiki/Liste_der_Nationalflaggen';

async function main() {
    const dirPath = path.resolve(`${__dirname}/../../www/decks/flaggen/cards`);

    const res = await fetch(WIKI_URL);
    const html = await res.text();

    const regex = /<b>\s*<a.*?title=\"(.*?)\".*?(\/wiki\/Datei\:.*?\.svg)/g;
    const flagDetails = await Promise.all([...html.matchAll(regex)].map(async match => {
        const [,title,svgPageUrl] = match;

        let id = title.toLowerCase();
        id = id.replaceAll(/\s+/g, ' ').replaceAll(' ', '_');
        id = id.replaceAll('ü', 'ue');
        id = id.replaceAll('ö', 'oe');
        id = id.replaceAll('ä', 'ae');
        id = id.replaceAll('ß', 'ss');
        id = id.replaceAll(/[^a-z0-9_\-]+/g, '');

        const svgPageRes = await fetch(`https://de.wikipedia.org${svgPageUrl}`);
        if (!svgPageRes.ok) throw new Error('failed to fetch ' + svgPageUrl);
        const svgPageHtml = await svgPageRes.text();

        const svgUrlRegex = /<a\s*href=\"(\/\/(.*?)\.svg)\".*?>\s*Originaldatei\s*<\/a>/g;
        const svgUrlMatch = svgPageHtml.matchAll(svgUrlRegex).next().value;
        const svgUrl = 'https:' + svgUrlMatch![1];

        const svgRes = await fetch(svgUrl);
        if (!svgRes.ok) throw new Error('failed to fetch ' + svgUrl);
        const svg = await svgRes.text();

        return {id, title, svg};
    }));

    await ($`rm ${dirPath}/*.htm`).catch(() => {});

    await Promise.all(flagDetails.map(async ({ id, title, svg }) => {
        const svgB64 = Buffer.from(svg, 'utf8').toString('base64');

        const html = `
<img src="data:image/svg+xml;base64,${svgB64}"
     style="width: 100%; height: auto; display: block;" />

-----

<p style="text-align: center; font-weight: bold; font-size: 1.3em;">${title}</p>
        `.trim();

        await fs.writeFile(`${dirPath}/${id}.htm`, html);
    }));
}

main()