#!/usr/bin/env bun

import path from 'path';
import fs from 'fs/promises';
import { $ } from "bun";

const WIKI_URL = 'https://de.wikipedia.org/wiki/Liste_der_Nationalflaggen';

async function asyncMapLimit(array, asyncFn, concurrency = 10) {
  const results = [];
  let index = 0;

  async function worker() {
    while (index < array.length) {
      const currentIndex = index++;
      results[currentIndex] = await asyncFn(array[currentIndex], currentIndex, array);
    }
  }

  // Create an array of workers up to concurrency limit
  const workers = Array.from({ length: Math.min(concurrency, array.length) }, () => worker());
  await Promise.all(workers);

  return results;
}

async function main() {
    const dirPath = path.resolve(`${__dirname}/../../www/decks/nationalflaggen/cards`);

    const res = await fetch(WIKI_URL);
    const html = await res.text();

    const regex = /<b>\s*<a.*?title=\"(.*?)\".*?(\/wiki\/Datei\:.*?\.svg)/g;
    const flagDetails = await asyncMapLimit([...html.matchAll(regex)], async match => {
        const [,title,svgPageUrl] = match;

        console.log(svgPageUrl);

        let id = title.toLowerCase();
        id = id.replaceAll(/\s+/g, ' ').replaceAll(' ', '_');
        id = id.replaceAll('ü', 'ue');
        id = id.replaceAll('ö', 'oe');
        id = id.replaceAll('ä', 'ae');
        id = id.replaceAll('ß', 'ss');
        id = id.replaceAll(/[^a-z0-9_\-]+/g, '');

        const svgPageRes = await fetch(`https://de.wikipedia.org${svgPageUrl}`);
        if (!svgPageRes.ok) throw new Error('failed to fetch ' + svgPageUrl);
        const svgPageHtml = await svgPageRes.text();

        const svgUrlRegex = /<a\s*href=\"(\/\/(.*?)\.svg)\".*?>\s*Originaldatei\s*<\/a>/g;
        const svgUrlMatch = svgPageHtml.matchAll(svgUrlRegex).next().value;
        const svgUrl = 'https:' + svgUrlMatch![1];

        const svgRes = await fetch(svgUrl);
        if (!svgRes.ok) throw new Error('failed to fetch ' + svgUrl);
        const svg = await svgRes.text();
        
        await fs.writeFile(`/tmp/${id}.svg`, svg);
        await $`rsvg-convert /tmp/${id}.svg -o /tmp/${id}.png -a -w 1800`;
        await $`convert /tmp/${id}.png -quality 80 /tmp/${id}.webp`;

        const webpBuffer = await fs.readFile(`/tmp/${id}.webp`);
        const imageUrl = `data:image/webp;base64,${webpBuffer.toString('base64')}`;

        return {id, title, imageUrl};
    });

    await ($`rm -f ${dirPath}/*.htm`).catch(() => {});

    await Promise.all(flagDetails.map(async ({ id, title, imageUrl }) => {
        const html = `
<img src="${imageUrl}" />

-----

<p style="text-align: center; font-weight: bold; font-size: 1.3em;">${title}</p>
        `.trim();

        await fs.writeFile(`${dirPath}/${id}.htm`, html);
    }));
}

main()